### ISSUE TITLE
Graphical texture error in Worms

### ISSUE THREAD

**Issue by kblood** [RobertPeip/PlayStation_MiSTer#3]
I was testing Worms and Worms World Party and I think they might have some interesting errors that can help with debugging the core. The ground layer in Worms 1 does not move correctly at all times. So sometimes the worms are standing above the ground. Rockets and such still hit the ground correctly and the holes are made correctly, and sometimes it is shown correctly with worms standing on the ground.

In Worms World Party you can get in game and for some reason everything is black, except the background.

Its not that I expect this to be fixed right away, but I figured this was something that might help with the development as a way to test the progress.

**Comment by atrac17** [comment]
![unknown](https://user-images.githubusercontent.com/32810066/143839972-1955316b-c453-4a71-963f-25a4312679b7.png)

**Comment by thehughhefner** [comment]
Please do not report any bugs yet.

**Comment by RobertPeip** [comment]
I'll close this one for now. Once the core is more stable, we can have a buglist.
