### ISSUE TITLE
mem card saving issue (Klonoa)

### ISSUE THREAD

**Issue by rester159** [RobertPeip/PlayStation_MiSTer#7]
Playing Klonoa when you create save A on memory card then overwrite with save B, save B remains in the mem card as long as you keep playing the game but if you turn off the system and reload save B is gone and save A is the only one you see. I was able to repro this consistently. Not sure whether I'm doing something wrong. I'm using the PSX_20230503.rbf from update_all

**Comment by RobertPeip** [comment]
wrong repo, please use mister psx repo
